name: Unit Tests
on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      INPUT_TOKEN: '${{ secrets.GEOFF_PAT }}'
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - run: python -m pytest